services:
  server:
    volumes:
      - /tmp/hls:/tmp/hls
      - /tmp/db:/tmp/db
      - /home/aidan/wsl-repos/pv_useful_scripts/multi_part_s3_upload/2026-04-11T04_40_00_TILL_2026-04-11T04_44_00.mkv:/app/dummy.mkv:ro
    command: ["./lucid_stream", "--out", "/tmp/hls", "--db", "/tmp/db/segments.db", "--file", "/app/dummy.mkv"]
    restart: "no"
